version: '2'
services:
    innovate-app:
        image: innovate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://innovate-postgresql:5432/innovate
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    innovate-postgresql:
        extends:
            file: postgresql.yml
            service: innovate-postgresql
